exclude: '^lnbits/static/vendor/.*'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-case-conflict
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ['--profile', 'black']
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: '50c5478ed9e10bf360335449280cf2a67f4edb7a'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-mock==4.0.15, types-protobuf==3.19.22]
        exclude: |
                (?x)(
                    ^lnbits/extensions/ |
                    ^lnbits/wallets/lnd_grpc_files/ |
                    ^tools/
                )
